import { useRouter } from "expo-router";
import { Pressable, ScrollView, Switch, Text, View } from "react-native";

import { ScreenContainer } from "@/components/screen-container";
import { useThemeContext } from "@/lib/theme-provider";

export default function AccessibilityScreen() {
  const router = useRouter();
  const { highContrast, setHighContrast, fontScale, setFontScale, reduceMotion, setReduceMotion } = useThemeContext();
  return <ScreenContainer className="px-5"><ScrollView contentContainerStyle={{ paddingBottom: 40 }}><Pressable onPress={() => router.back()}><Text className="mb-5 pt-2 font-semibold text-primary">‹ Назад</Text></Pressable><Text className="text-3xl font-bold text-foreground">Доступность</Text><Text className="mt-2 text-base leading-6 text-muted">Сделайте обучение комфортным для своего зрения, внимания и ритма.</Text><View className="mt-6 rounded-3xl border border-border bg-surface p-5"><View className="flex-row items-center justify-between"><View className="flex-1"><Text className="text-lg font-bold text-foreground">Высокий контраст</Text><Text className="mt-1 text-sm leading-5 text-muted">Максимально чёткие цвета текста, фона и границ.</Text></View><Switch value={highContrast} onValueChange={setHighContrast} /></View></View><View className="mt-4 rounded-3xl border border-border bg-surface p-5"><View className="flex-row items-center justify-between"><View className="flex-1"><Text className="text-lg font-bold text-foreground">Снижение движения</Text><Text className="mt-1 text-sm leading-5 text-muted">Уменьшает декоративные анимации и оставляет только необходимую обратную связь.</Text></View><Switch value={reduceMotion} onValueChange={setReduceMotion} /></View></View><View className="mt-4 rounded-3xl border border-border bg-surface p-5"><Text className="text-lg font-bold text-foreground">Размер текста</Text><View className="mt-4 flex-row gap-2">{[0.9, 1, 1.15].map((scale) => <Pressable key={scale} onPress={() => setFontScale(scale)} className={`flex-1 rounded-xl py-3 ${fontScale === scale ? "bg-primary" : "bg-background border border-border"}`}><Text className={`text-center font-bold ${fontScale === scale ? "text-white" : "text-foreground"}`}>{scale === 0.9 ? "Малый" : scale === 1 ? "Обычный" : "Крупный"}</Text></Pressable>)}</View></View><Pressable onPress={() => router.push("/focus" as never)} className="mt-4 rounded-3xl bg-[#172033] p-5"><Text className="text-lg font-bold text-white">Режим концентрации</Text><Text className="mt-2 text-sm leading-5 text-[#D8DDEA]">Открыть спокойный экран с одним следующим шагом без лишних блоков.</Text></Pressable></ScrollView></ScreenContainer>;
}
