import { useFocusEffect, useRouter } from "expo-router";
import { useCallback, useState } from "react";
import { Pressable, ScrollView, Text, TextInput, View } from "react-native";

import { ScreenContainer } from "@/components/screen-container";
import { createBookmarkCategory, loadBookmarks, type BookmarkState } from "@/lib/lesson-bookmarks";
import { getLesson } from "@/shared/course-data";

export default function BookmarksScreen() {
  const router = useRouter(); const [state, setState] = useState<BookmarkState | null>(null); const [category, setCategory] = useState<string | null>(null); const [newCategory, setNewCategory] = useState("");
  useFocusEffect(useCallback(() => { loadBookmarks().then((next) => { setState(next); setCategory((current) => current ?? next.categories[0]?.id ?? null); }); }, []));
  if (!state) return <ScreenContainer className="items-center justify-center"><Text className="text-muted">Загружаем закладки…</Text></ScreenContainer>;
  const visible = state.bookmarks.filter((item) => !category || item.categoryId === category).map((item) => ({ ...item, lesson: getLesson(item.lessonId) })).filter((item) => item.lesson);
  return <ScreenContainer className="px-5"><ScrollView contentContainerStyle={{ paddingBottom: 40 }}><Pressable onPress={() => router.back()}><Text className="mb-5 pt-2 font-semibold text-primary">‹ Назад</Text></Pressable><Text className="text-3xl font-bold text-foreground">Мои закладки</Text><Text className="mt-2 text-base leading-6 text-muted">Соберите сложные темы в личные категории и возвращайтесь к ним в удобный момент.</Text><View className="mt-5 flex-row flex-wrap gap-2">{state.categories.map((item) => <Pressable key={item.id} onPress={() => setCategory(item.id)} className={`rounded-full px-4 py-2 ${category === item.id ? "bg-primary" : "border border-border bg-surface"}`}><Text className={`font-bold ${category === item.id ? "text-white" : "text-foreground"}`}>{item.name}</Text></Pressable>)}</View><View className="mt-4 flex-row gap-2"><TextInput value={newCategory} onChangeText={setNewCategory} placeholder="Своя категория" placeholderTextColor="#667085" className="flex-1 rounded-xl border border-border bg-surface px-3 py-3 text-foreground" /><Pressable onPress={async () => { const next = await createBookmarkCategory(newCategory); setState(next); setCategory(next.categories[next.categories.length - 1]?.id ?? null); setNewCategory(""); }} className="items-center justify-center rounded-xl bg-primary px-4"><Text className="font-bold text-white">Создать</Text></Pressable></View><View className="mt-5 gap-3">{visible.length ? visible.map((item) => <Pressable key={`${item.lessonId}-${item.categoryId}`} onPress={() => router.push(`/lesson/${item.lessonId}` as never)} className="rounded-3xl border border-border bg-surface p-5"><Text className="text-sm font-bold text-primary">{state.categories.find((entry) => entry.id === item.categoryId)?.name}</Text><Text className="mt-2 text-lg font-bold text-foreground">{item.lesson?.title}</Text><Text className="mt-2 text-sm leading-5 text-muted">{item.lesson?.goal}</Text><Text className="mt-3 font-bold text-primary">Открыть урок →</Text></Pressable>) : <View className="rounded-3xl bg-[#E9EAFE] p-5"><Text className="text-lg font-bold text-foreground">Здесь пока пусто</Text><Text className="mt-2 text-sm leading-5 text-[#42446F]">Откройте урок и добавьте его в одну из категорий.</Text></View>}</View></ScrollView></ScreenContainer>;
}
