import { useRouter } from "expo-router";
import { useState } from "react";
import { Pressable, ScrollView, Text, TextInput, View } from "react-native";
import * as DocumentPicker from "expo-document-picker";
import * as FileSystem from "expo-file-system/legacy";

import { ScreenContainer } from "@/components/screen-container";
import { summarizeCsv, type CsvSummary } from "@/shared/csv-utils";

const demo = "day,orders,revenue\nMonday,12,240\nTuesday,15,330\nWednesday,9,180\nThursday,18,405";

export default function CsvLabScreen() {
  const router = useRouter(); const [source, setSource] = useState(demo); const [summary, setSummary] = useState<CsvSummary | null>(null); const [error, setError] = useState(""); const [fileName, setFileName] = useState("");
  const analyze = (text = source) => { try { setError(""); setSummary(summarizeCsv(text)); } catch (reason) { setSummary(null); setError(reason instanceof Error ? reason.message : "Не удалось разобрать CSV."); } };
  const pick = async () => { const result = await DocumentPicker.getDocumentAsync({ type: ["text/csv", "text/comma-separated-values", "text/plain"], copyToCacheDirectory: true }); if (result.canceled) return; const asset = result.assets[0]; try { const text = await FileSystem.readAsStringAsync(asset.uri, { encoding: FileSystem.EncodingType.UTF8 }); setSource(text.slice(0, 200000)); setFileName(asset.name); analyze(text); } catch { setError("Не удалось прочитать этот файл. Попробуйте небольшой текстовый CSV в UTF‑8."); } };
  return <ScreenContainer className="px-5"><ScrollView contentContainerStyle={{ paddingBottom: 40 }} keyboardShouldPersistTaps="handled"><Pressable onPress={() => router.back()}><Text className="mb-5 pt-2 font-semibold text-primary">‹ Назад</Text></Pressable><Text className="text-3xl font-bold text-foreground">CSV-лаборатория</Text><Text className="mt-2 text-base leading-6 text-muted">Выберите небольшой CSV или вставьте таблицу. Файл читается только локально, не отправляется ИИ и не загружается на сервер.</Text><View className="mt-5 flex-row gap-3"><Pressable onPress={pick} className="flex-1 items-center rounded-2xl bg-primary py-4"><Text className="font-bold text-white">Выбрать CSV</Text></Pressable><Pressable onPress={() => { setSource(demo); setFileName("Демонстрация"); analyze(demo); }} className="flex-1 items-center rounded-2xl border border-border bg-surface py-4"><Text className="font-bold text-foreground">Демо</Text></Pressable></View>{fileName ? <Text className="mt-3 text-sm text-success">Файл: {fileName}</Text> : null}<TextInput value={source} onChangeText={setSource} multiline autoCapitalize="none" autoCorrect={false} textAlignVertical="top" className="mt-5 min-h-44 rounded-3xl bg-[#172033] px-4 py-4 font-mono text-white" /><Pressable onPress={() => analyze()} className="mt-4 items-center rounded-2xl bg-primary py-4"><Text className="font-bold text-white">Проанализировать таблицу</Text></Pressable>{error ? <Text className="mt-4 rounded-xl bg-[#FFF1E8] p-3 text-sm text-warning">{error}</Text> : null}{summary ? <View className="mt-5 gap-4"><View className="rounded-3xl bg-[#E9EAFE] p-5"><Text className="text-lg font-bold text-foreground">Короткий итог</Text><Text className="mt-2 text-sm text-[#42446F]">Строк: {summary.rowCount}. Столбцы: {summary.headers.join(", ")}.</Text></View><View className="rounded-3xl border border-border bg-surface p-5"><Text className="text-lg font-bold text-foreground">Числовые показатели</Text>{summary.numeric.length ? summary.numeric.map((item) => <Text key={item.column} className="mt-3 text-sm leading-5 text-muted"><Text className="font-bold text-foreground">{item.column}: </Text>сумма {item.sum.toFixed(2)}, среднее {item.mean.toFixed(2)} ({item.count} значений)</Text>) : <Text className="mt-2 text-sm text-muted">Числовые столбцы не найдены.</Text>}</View><View className="rounded-3xl border border-border bg-surface p-5"><Text className="text-lg font-bold text-foreground">Первые строки</Text>{summary.sample.map((row, index) => <Text key={`${index}-${row.join("|")}`} className="mt-2 font-mono text-xs text-muted">{row.join(" | ")}</Text>)}</View><Text className="text-sm leading-5 text-muted">Следующий шаг: перенесите эту логику в проектный трек «Анализ данных» с помощью pandas.</Text></View> : null}</ScrollView></ScreenContainer>;
}
