import { useFocusEffect, useRouter } from "expo-router";
import { useCallback, useState } from "react";
import { Pressable, ScrollView, Text, View } from "react-native";

import { ScreenContainer } from "@/components/screen-container";
import { CelebrationBanner } from "@/components/celebration-banner";
import { loadToolkit, updateToolkit, type ToolkitState } from "@/lib/study-toolkit";
import { clubChallenges, codeAssembly, codeExplanation, commonErrors, dailyChallenges, glossary, knowledgeMap, learningRoute, miniProjects, realWorldStories, versionGuide } from "@/shared/study-lab-data";

type Section = "route" | "practice" | "projects" | "reference" | "community";
const sections: [Section, string][] = [["route", "Маршрут"], ["practice", "Практика"], ["projects", "Проекты"], ["reference", "Справка"], ["community", "Клуб"]];

export default function StudyLabScreen() {
  const router = useRouter();
  const [section, setSection] = useState<Section>("route");
  const [toolkit, setToolkit] = useState<ToolkitState | null>(null);
  const [diagnostic, setDiagnostic] = useState<number | null>(null);
  const [assembled, setAssembled] = useState<string[]>([]);
  const [explanation, setExplanation] = useState<number | null>(null);
  const [hintLevel, setHintLevel] = useState(0);
  const [dailyDone, setDailyDone] = useState(false);
  const [celebration, setCelebration] = useState<string | null>(null);

  useFocusEffect(useCallback(() => { loadToolkit().then(setToolkit); }, []));
  const todayChallenge = dailyChallenges[new Date().getDay() % dailyChallenges.length];
  const isAssemblyCorrect = assembled.join("|") === codeAssembly.answer.join("|");
  const nextHint = ["Подсказка 1: сначала прочитайте условие и назовите главную конструкцию.", "Подсказка 2: выпишите переменные и результат, который должен получиться.", "Подсказка 3: сравните свой план с минимальным примером урока."];

  const saveDiagnostic = async (score: number) => { setDiagnostic(score); setToolkit(await updateToolkit({ diagnosticScore: score })); };
  const unlockAchievement = async (id: string) => { if (!toolkit || toolkit.achievements.includes(id)) return; setToolkit(await updateToolkit({ achievements: [...toolkit.achievements, id] })); setCelebration(id); };

  const content = (() => {
    if (section === "route") return <View className="gap-4"><View className="rounded-3xl bg-[#E9EAFE] p-5"><Text className="text-sm font-bold text-primary">АДАПТИВНЫЙ МАРШРУТ</Text><Text className="mt-2 text-xl font-bold text-foreground">Учимся не быстрее, а понятнее</Text><Text className="mt-2 text-sm leading-5 text-[#42446F]">Результаты быстрых тестов и ваша диагностика помогают выбрать спокойный следующий шаг.</Text></View><View className="rounded-3xl border border-border bg-surface p-5"><Text className="text-lg font-bold text-foreground">Входная диагностика</Text><Text className="mt-2 text-sm leading-5 text-muted">Как вы оцениваете уверенность в базовом Python?</Text><View className="mt-4 flex-row gap-2">{[[1, "Начинаю"], [2, "Практикую"], [3, "Уверенно"]].map(([value, label]) => <Pressable key={String(value)} onPress={() => saveDiagnostic(Number(value))} className={`flex-1 rounded-xl p-3 ${diagnostic === value || toolkit?.diagnosticScore === value ? "bg-primary" : "bg-background border border-border"}`}><Text className={`text-center text-xs font-bold ${diagnostic === value || toolkit?.diagnosticScore === value ? "text-white" : "text-foreground"}`}>{label}</Text></Pressable>)}</View></View>{learningRoute.map((item, index) => <View key={item.title} className="rounded-3xl border border-border bg-surface p-5"><Text className="text-sm font-bold text-primary">ШАГ {index + 1}</Text><Text className="mt-1 text-lg font-bold text-foreground">{item.title}</Text><Text className="mt-2 text-sm leading-5 text-muted">{item.text}</Text></View>)}<View className="rounded-3xl border border-border bg-surface p-5"><Text className="text-lg font-bold text-foreground">Интервальное повторение</Text><Text className="mt-2 text-sm leading-5 text-muted">Сегодня повторите одну тему с ошибочным тестом, через 3 дня — решите похожую задачу, через неделю — примените её в проекте.</Text></View></View>;
    if (section === "practice") return <View className="gap-4"><View className="rounded-3xl bg-[#172033] p-5"><Text className="text-sm font-bold text-[#C9C9FF]">ЗАДАЧА ДНЯ</Text><Text className="mt-2 text-lg font-bold text-white">{todayChallenge}</Text><Pressable onPress={async () => { setDailyDone(true); await unlockAchievement("daily"); }} className="mt-4 items-center rounded-2xl bg-primary py-3"><Text className="font-bold text-white">{dailyDone ? "✓ Отмечено" : "Я попробовал(а)"}</Text></Pressable></View><View className="rounded-3xl border border-border bg-surface p-5"><Text className="text-lg font-bold text-foreground">Собери код</Text><Text className="mt-2 text-sm text-muted">Нажмите строки в правильном порядке.</Text><View className="mt-3 gap-2">{codeAssembly.lines.map((line) => <Pressable key={line} onPress={() => setAssembled((current) => current.includes(line) ? current.filter((item) => item !== line) : [...current, line])} className={`rounded-xl p-3 ${assembled.includes(line) ? "bg-[#E9EAFE]" : "bg-background border border-border"}`}><Text className="font-mono text-xs text-foreground">{line}</Text></Pressable>)}</View>{assembled.length === 2 ? <Text className={`mt-3 font-semibold ${isAssemblyCorrect ? "text-success" : "text-warning"}`}>{isAssemblyCorrect ? "Верно: сначала создаём переменную, затем используем её." : "Порядок пока не совпал. Сначала нужно создать переменную."}</Text> : null}</View><View className="rounded-3xl border border-border bg-surface p-5"><Text className="text-lg font-bold text-foreground">Объясни код</Text><Text className="mt-2 font-mono text-xs text-foreground">{codeExplanation.code}</Text><Text className="mt-3 text-sm text-muted">{codeExplanation.question}</Text><View className="mt-3 gap-2">{codeExplanation.options.map((option, index) => <Pressable key={option} onPress={() => setExplanation(index)} className={`rounded-xl p-3 ${explanation === index ? "bg-[#E9EAFE]" : "bg-background border border-border"}`}><Text className="font-semibold text-foreground">{option}</Text></Pressable>)}</View>{explanation !== null ? <Text className={`mt-3 text-sm ${explanation === codeExplanation.answer ? "text-success" : "text-warning"}`}>{codeExplanation.explanation}</Text> : null}</View><View className="rounded-3xl border border-border bg-surface p-5"><Text className="text-lg font-bold text-foreground">Подсказки без спешки</Text><Text className="mt-2 text-sm text-muted">{hintLevel ? nextHint[hintLevel - 1] : "Сначала попробуйте решить задачу сами."}</Text><Pressable onPress={() => setHintLevel((level) => Math.min(3, level + 1))} className="mt-3 items-center rounded-xl bg-primary py-3"><Text className="font-bold text-white">Следующая подсказка</Text></Pressable></View></View>;
    if (section === "projects") return <View className="gap-3">{miniProjects.map((project) => <View key={project.id} className="rounded-3xl border border-border bg-surface p-5"><Text className="text-sm font-bold text-primary">{project.level}</Text><Text className="mt-1 text-xl font-bold text-foreground">{project.title}</Text><View className="mt-3 gap-1">{project.steps.map((step, index) => <Text key={step} className="text-sm leading-5 text-muted">{index + 1}. {step}</Text>)}</View><Pressable onPress={() => unlockAchievement(`project-${project.id}`)} className="mt-4 items-center rounded-xl bg-[#E9EAFE] py-3"><Text className="font-bold text-primary">Начать план проекта</Text></Pressable></View>)}</View>;
    if (section === "reference") return <View className="gap-4"><View className="rounded-3xl border border-border bg-surface p-5"><Text className="text-lg font-bold text-foreground">Карта знаний</Text>{knowledgeMap.map((row, index) => <View key={String(index)} className="mt-3 flex-row flex-wrap gap-2">{row.map((item) => <View key={item} className="rounded-full bg-[#E9EAFE] px-3 py-2"><Text className="text-xs font-bold text-primary">{item}</Text></View>)}</View>)}</View><View className="rounded-3xl border border-border bg-surface p-5"><Text className="text-lg font-bold text-foreground">Глоссарий</Text>{glossary.map(([term, description]) => <Text key={term} className="mt-3 text-sm leading-5 text-muted"><Text className="font-bold text-foreground">{term}. </Text>{description}</Text>)}</View><View className="rounded-3xl border border-border bg-surface p-5"><Text className="text-lg font-bold text-foreground">Словарь ошибок</Text>{commonErrors.map(([error, description]) => <Text key={error} className="mt-3 text-sm leading-5 text-muted"><Text className="font-bold text-warning">{error}. </Text>{description}</Text>)}</View><View className="rounded-3xl border border-border bg-surface p-5"><Text className="text-lg font-bold text-foreground">Python в жизни</Text>{realWorldStories.map((story) => <Text key={story} className="mt-3 text-sm leading-5 text-muted">• {story}</Text>)}</View><View className="rounded-3xl border border-border bg-surface p-5"><Text className="text-lg font-bold text-foreground">Совместимость версий</Text>{versionGuide.map(([version, description]) => <Text key={version} className="mt-3 text-sm leading-5 text-muted"><Text className="font-bold text-foreground">{version}. </Text>{description}</Text>)}</View></View>;
    return <View className="gap-4"><View className="rounded-3xl border border-border bg-surface p-5"><Text className="text-lg font-bold text-foreground">Клуб задач</Text><Text className="mt-2 text-sm text-muted">Выберите тему недели и решайте её в своём темпе.</Text>{clubChallenges.map((challenge) => <View key={challenge} className="mt-3 rounded-xl bg-background p-3"><Text className="text-sm text-foreground">{challenge}</Text></View>)}</View><View className="rounded-3xl border border-border bg-surface p-5"><Text className="text-lg font-bold text-foreground">Карточки парного повторения</Text>{[["Объясните", "Почему у if после условия стоит двоеточие?"], ["Спросите", "Чем print отличается от return?"], ["Проверьте", "Что вернёт range(3)?"]].map(([title, text]) => <View key={title} className="mt-3 rounded-xl bg-[#E9EAFE] p-3"><Text className="text-xs font-bold text-primary">{title}</Text><Text className="mt-1 text-sm text-foreground">{text}</Text></View>)}</View><Pressable onPress={() => router.push("/mentor-request" as never)} className="items-center rounded-2xl bg-primary py-4"><Text className="font-bold text-white">Подготовить заявку наставнику</Text></Pressable></View>;
  })();

  return <ScreenContainer className="px-5"><ScrollView contentContainerStyle={{ paddingBottom: 40 }} showsVerticalScrollIndicator={false}><Pressable onPress={() => router.back()}><Text className="mb-5 pt-2 font-semibold text-primary">‹ Назад</Text></Pressable><Text className="text-3xl font-bold text-foreground">Учебная студия</Text><Text className="mt-2 text-base leading-6 text-muted">Все новые способы учиться, повторять, строить проекты и закреплять знания.</Text><Pressable onPress={() => router.push("/mastery-lab" as never)} className="mt-4 rounded-3xl bg-[#111426] p-5"><Text className="text-xs font-bold tracking-wide text-[#C9C9FF]">НОВОЕ · 24 УЛУЧШЕНИЯ</Text><Text className="mt-2 text-xl font-bold text-white">Открыть мастерскую роста →</Text><Text className="mt-2 text-sm leading-5 text-[#D3D7FF]">Отладка, пошаговый код, планы, проекты, Git, SQLite, диагностика и резервные копии.</Text></Pressable><View className="mt-5 flex-row flex-wrap gap-2">{sections.map(([id, label]) => <Pressable key={id} onPress={() => setSection(id)} className={`rounded-full px-4 py-2 ${section === id ? "bg-primary" : "bg-surface border border-border"}`}><Text className={`text-sm font-bold ${section === id ? "text-white" : "text-foreground"}`}>{label}</Text></Pressable>)}</View>{celebration ? <CelebrationBanner title={celebration === "daily" ? "Ежедневная цель выполнена" : "Шаг к мини-проекту"} description="Небольшая регулярная практика действительно складывается в большой навык." /> : null}<View className="mt-5">{content}</View></ScrollView></ScreenContainer>;
}
