import type { CourseData } from "./course-types";

type Stage = "junior" | "middle" | "senior" | "applied";
type Seed = { stage: Stage; title: string; goal: string; analogy: string; code: string; explanation: string };
const seeds: Seed[] = [
  { stage: "junior", title: "React и компоненты", goal: "Понять роль React.", analogy: "React — коробка конструктора: экран собирается из маленьких деталей.", code: "function App() { return <h1>Привет!</h1>; }", explanation: "Компонент возвращает описание интерфейса." },
  { stage: "junior", title: "JSX", goal: "Прочитать JSX.", analogy: "JSX — чертёж того, что увидит человек.", code: "const title = <h1>Урок React</h1>;", explanation: "JSX похож на HTML, но живёт внутри JavaScript." },
  { stage: "junior", title: "Первый компонент", goal: "Создать компонент.", analogy: "Компонент — отдельная деталь конструктора с именем.", code: "function Greeting() { return <p>Добрый день</p>; }", explanation: "Имя компонента начинается с большой буквы." },
  { stage: "junior", title: "Вставка значения", goal: "Показать данные в JSX.", analogy: "Фигурные скобки — окошко, через которое в макет попадают данные.", code: "const name = 'Аня';\nreturn <h1>Привет, {name}</h1>;", explanation: "В фигурных скобках можно использовать выражение JavaScript." },
  { stage: "junior", title: "Props", goal: "Передать данные компоненту.", analogy: "Props — записка от родителя к ребёнку-компоненту.", code: "function Greeting({ name }: { name: string }) { return <p>{name}</p>; }", explanation: "Компонент получает name через props." },
  { stage: "junior", title: "Повторное использование", goal: "Использовать компонент несколько раз.", analogy: "Одну деталь конструктора можно поставить в разные места.", code: "<Greeting name=\"Аня\" />\n<Greeting name=\"Миша\" />", explanation: "Один компонент рисуется с разными данными." },
  { stage: "middle", title: "State", goal: "Хранить меняющееся состояние.", analogy: "State — табло, которое помнит текущее число.", code: "const [count, setCount] = useState(0);", explanation: "count хранит значение, setCount его меняет." },
  { stage: "middle", title: "Кнопка", goal: "Ответить на нажатие.", analogy: "onClick — звонок, который запускает действие.", code: "<button onClick={() => setCount(count + 1)}>+1</button>", explanation: "Клик вызывает обновление состояния." },
  { stage: "middle", title: "Не менять state напрямую", goal: "Обновлять состояние правильно.", analogy: "Табло меняют через пульт, а не рукой внутри механизма.", code: "setCount((current) => current + 1);", explanation: "Функциональная форма берёт актуальное значение." },
  { stage: "middle", title: "Список", goal: "Показать массив.", analogy: "map — конвейер, который превращает каждую карточку в элемент экрана.", code: "topics.map((topic) => <li key={topic}>{topic}</li>)", explanation: "key помогает React узнавать элементы списка." },
  { stage: "middle", title: "Условный UI", goal: "Показать нужный вариант.", analogy: "Условие — светофор для частей интерфейса.", code: "return ready ? <p>Готово</p> : <p>Учимся</p>;", explanation: "Тернарный оператор выбирает один из двух вариантов." },
  { stage: "middle", title: "Контролируемое поле", goal: "Связать input и state.", analogy: "Поле ввода и табло смотрят друг на друга.", code: "<input value={name} onChange={(event) => setName(event.target.value)} />", explanation: "Значение поля берётся из state и обновляет его." },
  { stage: "senior", title: "useEffect", goal: "Понять побочный эффект.", analogy: "Effect — напоминание сделать действие после обновления экрана.", code: "useEffect(() => { document.title = title; }, [title]);", explanation: "Effect запускается, когда меняется title." },
  { stage: "senior", title: "Зависимости effect", goal: "Указать, что отслеживать.", analogy: "Массив зависимостей — список сигналов для напоминания.", code: "useEffect(() => { console.log(count); }, [count]);", explanation: "Effect реагирует на изменение count." },
  { stage: "senior", title: "Подъём состояния", goal: "Поделиться данными.", analogy: "Общее табло ставят у родителя, чтобы его видели дети.", code: "function App() { const [theme, setTheme] = useState('dark'); return <Panel theme={theme} />; }", explanation: "Общее состояние живёт в ближайшем общем родителе." },
  { stage: "senior", title: "Композиция", goal: "Собирать экран из частей.", analogy: "Композиция — собирать дом из комнат, а не писать весь дом одной строкой.", code: "<Layout><Sidebar /><Content /></Layout>", explanation: "Компоненты удобно вкладывать друг в друга." },
  { stage: "senior", title: "Мемоизация", goal: "Не делать лишнюю работу.", analogy: "useMemo — закладка с уже готовым ответом.", code: "const total = useMemo(() => items.length, [items]);", explanation: "Значение пересчитывается, когда меняются items." },
  { stage: "senior", title: "Ошибка в UI", goal: "Показывать понятную ошибку.", analogy: "Ошибка — дорожный знак, а не тупик.", code: "return error ? <p role=\"alert\">Не удалось загрузить</p> : <List />;", explanation: "Пользователь видит ясное состояние вместо пустого экрана." },
  { stage: "applied", title: "План проекта", goal: "Разбить приложение на компоненты.", analogy: "План — карта комнат до строительства дома.", code: "const screens = ['Список', 'Фильтр', 'Форма'];", explanation: "Список частей помогает начать проект спокойно." },
  { stage: "applied", title: "Модель задачи", goal: "Описать данные.", analogy: "Модель — карточка, у которой всегда одинаковые поля.", code: "type Task = { id: string; title: string; done: boolean };", explanation: "Тип Task держит данные проекта в порядке." },
  { stage: "applied", title: "Список задач", goal: "Собрать список из state.", analogy: "State хранит стопку карточек задач.", code: "const [tasks, setTasks] = useState<Task[]>([]);", explanation: "State содержит типизированный массив задач." },
  { stage: "applied", title: "Фильтр", goal: "Показать открытые задачи.", analogy: "Фильтр — папка, в которую попадают только нужные карточки.", code: "const open = tasks.filter((task) => !task.done);", explanation: "filter оставляет незавершённые задачи." },
  { stage: "applied", title: "Тест компонента", goal: "Проверить видимое поведение.", analogy: "Тест — контрольный вопрос: видит ли человек ожидаемый результат.", code: "expect(screen.getByText('Готово')).toBeTruthy();", explanation: "Тест проверяет важный текст интерфейса." },
  { stage: "applied", title: "Итоговый проект", goal: "Собрать понятный мини-интерфейс.", analogy: "Итог — маленькая выставка аккуратных компонентов.", code: "<TaskApp initialTheme=\"dark\" />", explanation: "Проект объединяет компоненты, state, доступность и README." },
];
const titles: Record<Stage, string> = { junior: "Том I · Junior: компоненты и JSX", middle: "Том II · Middle: состояние и события", senior: "Том III · Senior: архитектура интерфейса", applied: "Том IV · Проекты и практика" };
export const reactCourseContent: CourseData = { volumes: (["junior", "middle", "senior", "applied"] as Stage[]).map((stage) => ({ id: stage, title: titles[stage], lessons: seeds.filter((seed) => seed.stage === stage).map((seed, index) => { const number = (["junior", "middle", "senior", "applied"] as Stage[]).slice(0, ["junior", "middle", "senior", "applied"].indexOf(stage)).reduce((total, prior) => total + seeds.filter((seed) => seed.stage === prior).length, 0) + index + 1; return { id: `react-${stage}-${number}`, number, title: seed.title, goal: seed.goal, analogy: seed.analogy, code: seed.code, body: `Цель. ${seed.goal}\n\nАналогия. ${seed.analogy}\n\n### Пример\n\n${seed.code}\n\nРазбор. ${seed.explanation}\n\n### Практика\n\n#### Задача 1\nПовторите короткий пример.\n\nПодсказка. Меняйте один маленький шаг.\n\nРазбор решения. ${seed.explanation}\n\n#### Задача 2\nОбъясните пример своими словами.\n\nПодсказка. Назовите компонент, данные или состояние.\n\nРазбор решения. ${seed.explanation}\n\n#### Задача 3\nСделайте маленькое безопасное изменение.\n\nПодсказка. Не переписывайте пример целиком.\n\nРазбор решения. Проверьте, что интерфейс всё ещё описан понятно.` }; }) })) };
